/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef types_CONSTANTS_H
#define types_CONSTANTS_H

#include "types_types.h"

namespace de { namespace dfki { namespace tecs { namespace examples { namespace helloworld {

class typesConstants {
 public:
  typesConstants();

};

extern const typesConstants g_types_constants;

}}}}} // namespace

#endif
