/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "types_constants.h"

namespace de { namespace dfki { namespace tecs { namespace examples { namespace helloworld {

const typesConstants g_types_constants;

typesConstants::typesConstants() {
}

}}}}} // namespace

